# Generated by Django 5.2.4 on 2026-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search_app', '0002_saveddoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
