"""
Django settings for doctor_search project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- ENVIRONMENT DETECTION (Local vs Production) ---
# If 'RENDER' env var exists, we are in production.
IN_PRODUCTION = 'RENDER' in os.environ

# SECURITY WARNING: keep the secret key used in production secret!
# On Render, set this in Environment Variables. Locally, it uses the insecure fallback.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-rj&j9icawkvhdvpem2eh5i$#$rhk#z!kgb#^3ocf^$8x@hhmtr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IN_PRODUCTION

if IN_PRODUCTION:
    hosts = os.environ.get('ALLOWED_HOSTS', '')
    ALLOWED_HOSTS = [host.strip() for host in hosts.split(',') if host.strip()]
    # Fallback: If no hosts are set, allow all Render subdomains
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['.onrender.com']
else:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Third Party Apps ---
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',            # Required for React to talk to Django
    'django_filters',

    # --- Local Apps ---
    'doctor_search_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",   # <--- 1. Static Files (Must be here)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',        # <--- 2. CORS (Must be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls' # Make sure your main folder is actually named 'core'. If it's 'doctor_search_backend', change this.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# --- DATABASE CONFIGURATION (Hybrid) ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Local: Uses SQLite
        # Production: Reads DATABASE_URL env var (Supabase)
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- STATIC FILES (WhiteNoise) ---
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Where files go in production

if IN_PRODUCTION:
    # Use WhiteNoise to serve static files (CSS/JS) on Render
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CUSTOM USER MODEL ---
AUTH_USER_MODEL = 'doctor_search_app.User'


# --- REST FRAMEWORK ---
# --- REST FRAMEWORK ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [  # <-- Fixed typo (added the 'S')
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    # 1. Force Django to ONLY use JSON in production to prevent 500 errors
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# 2. Only add the "Pretty HTML" view if you are testing locally on your laptop
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append(
        'rest_framework.renderers.BrowsableAPIRenderer'
    )

# --- CORS CONFIG ---
if IN_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [x.strip() for x in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if x.strip()]
    CORS_ALLOWED_ORIGINS.append('https://docrank.jbnmedia.org')
else:
    CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
]


# --- EMAIL SETTINGS ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 465)) # Default to 465
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = os.environ.get('RESEND_API_KEY')
EMAIL_TIMEOUT = 10 # Stops the connection from hanging forever
# Format example: "Doctor Search <noreply@yourdomain.com>"
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True') == 'True'
# settings.py
RESEND_API_KEY = os.environ.get('RESEND_API_KEY')